package com.youngsee.dual.envmnt;

public class AirConStatsInfo {

	int command1;
	int rt1_sensor_error;
	int rt2_sensor_error;
	int humidity_sensor_error;
	int eeprom_setting_error;
	int slave_onoff;
	int high_temp_alarm;
	int low_temp_alarm;
	int smoke_alarm;
	int compressor_high_pressure_alarm;
	int compressor_low_pressure_alarm;
	int dooropen_alarm;
	int vibration_alarm;
	int compressor_status;
	int eheating_status;
	int inside_draftfan_status;
	int outside_draftfan_status;
	int emergency_draftfan_status;
	int inside_draftfan2_status;
	int outside_draftfan2_status;
	int power_input_undervoltage_protect;
	int power_input_overvoltage_protect;
	int ultra_temp_alarm;
	int crc1;
	int command2;
	float rt1_temp;
	float rt2_temp;
	float humidity;
	int inner_draftfan1_speed;
	int inner_draftfan2_speed;
	int outer_draftfan1_speed;
	int outer_draftfan2_speed;
	float refrigeration_start_temp;
	float refrigeration_stop_temp;
	float heating_start_temp;
	float heating_stop_temp;
	float high_temp_alarm_setting;
	float low_temp_alarm_setting;
	float ultra_temp_alarm_setting;
	float airconditioner_return_diff;
	float inner_recycle_stop_temp;
	float inner_recycle_running_temp;
	float inner_recycle_acceleration_temp;
	float inner_recycle_highspeed_temp;
	float inner_recycle_fullspeed_temp;
	float outer_recycle_stop_temp;
	float outer_recycle_running_temp;
	float outer_recycle_acceleration_temp;
	float outer_recycle_highspeed_temp;
	float outer_recycle_fullspeed_temp;
	float rt1_temp_sensor_correct_value;
	float rt2_temp_sensor_correct_value;
	int inner_recycle_draftfan1_setting;
	int inner_recycle_draftfan2_setting;
	int outer_recycle_draftfan1_setting;
	int outer_recycle_draftfan2_setting;
	int compressor_setting;
	int eheating_setting;
	int relay_a_setting;
	int relay_b_setting;
	int relay_c_setting;
	int p1_protect_input_setting;
	int p2_protect_input_setting;
	int rt1_sensor_enable_setting;
	int rt2_sensor_enable_setting;
	int humidity_sensor_enable_setting;
	int underpressure_alarm_setting;
	int overpressure_alarm_setting;
	int inside_draftfan_feedback_pulse;
	int outside_draftfan_feedback_pulse;
	int mute_mode_setting;
	int system_onoff;
	int buzzer_mode;
	int lcd_contrast_setting;
	int crc2;

	public AirConStatsInfo() {
		
	}

	public AirConStatsInfo(AirConStatsInfo info) {
		command1 = info.command1;
		rt1_sensor_error = info.rt1_sensor_error;
		rt2_sensor_error = info.rt2_sensor_error;
		humidity_sensor_error = info.humidity_sensor_error;
		eeprom_setting_error = info.eeprom_setting_error;
		slave_onoff = info.slave_onoff;
		high_temp_alarm = info.high_temp_alarm;
		low_temp_alarm = info.low_temp_alarm;
		smoke_alarm = info.smoke_alarm;
		compressor_high_pressure_alarm = info.compressor_high_pressure_alarm;
		compressor_low_pressure_alarm = info.compressor_low_pressure_alarm;
		dooropen_alarm = info.dooropen_alarm;
		vibration_alarm = info.vibration_alarm;
		compressor_status = info.compressor_status;
		eheating_status = info.eheating_status;
		inside_draftfan_status = info.inside_draftfan_status;
		outside_draftfan_status = info.outside_draftfan_status;
		emergency_draftfan_status = info.emergency_draftfan_status;
		inside_draftfan2_status = info.inside_draftfan2_status;
		outside_draftfan2_status = info.outside_draftfan2_status;
		power_input_undervoltage_protect = info.power_input_undervoltage_protect;
		power_input_overvoltage_protect = info.power_input_overvoltage_protect;
		ultra_temp_alarm = info.ultra_temp_alarm;
		crc1 = info.crc1;
		command2 = info.command2;
		rt1_temp = info.rt1_temp;
		rt2_temp = info.rt2_temp;
		humidity = info.humidity;
		inner_draftfan1_speed = info.inner_draftfan1_speed;
		inner_draftfan2_speed = info.inner_draftfan2_speed;
		outer_draftfan1_speed = info.outer_draftfan1_speed;
		outer_draftfan2_speed = info.outer_draftfan2_speed;
		refrigeration_start_temp = info.refrigeration_start_temp;
		refrigeration_stop_temp = info.refrigeration_stop_temp;
		heating_start_temp = info.heating_start_temp;
		heating_stop_temp = info.heating_stop_temp;
		high_temp_alarm_setting = info.high_temp_alarm_setting;
		low_temp_alarm_setting = info.low_temp_alarm_setting;
		ultra_temp_alarm_setting = info.ultra_temp_alarm_setting;
		airconditioner_return_diff = info.airconditioner_return_diff;
		inner_recycle_stop_temp = info.inner_recycle_stop_temp;
		inner_recycle_running_temp = info.inner_recycle_running_temp;
		inner_recycle_acceleration_temp = info.inner_recycle_acceleration_temp;
		inner_recycle_highspeed_temp = info.inner_recycle_highspeed_temp;
		inner_recycle_fullspeed_temp = info.inner_recycle_fullspeed_temp;
		outer_recycle_stop_temp = info.outer_recycle_stop_temp;
		outer_recycle_running_temp = info.outer_recycle_running_temp;
		outer_recycle_acceleration_temp = info.outer_recycle_acceleration_temp;
		outer_recycle_highspeed_temp = info.outer_recycle_highspeed_temp;
		outer_recycle_fullspeed_temp = info.outer_recycle_fullspeed_temp;
		rt1_temp_sensor_correct_value = info.rt1_temp_sensor_correct_value;
		rt2_temp_sensor_correct_value = info.rt2_temp_sensor_correct_value;
		inner_recycle_draftfan1_setting = info.inner_recycle_draftfan1_setting;
		inner_recycle_draftfan2_setting = info.inner_recycle_draftfan2_setting;
		outer_recycle_draftfan1_setting = info.outer_recycle_draftfan1_setting;
		outer_recycle_draftfan2_setting = info.outer_recycle_draftfan2_setting;
		compressor_setting = info.compressor_setting;
		eheating_setting = info.eheating_setting;
		relay_a_setting = info.relay_a_setting;
		relay_b_setting = info.relay_b_setting;
		relay_c_setting = info.relay_c_setting;
		p1_protect_input_setting = info.p1_protect_input_setting;
		p2_protect_input_setting = info.p2_protect_input_setting;
		rt1_sensor_enable_setting = info.rt1_sensor_enable_setting;
		rt2_sensor_enable_setting = info.rt2_sensor_enable_setting;
		humidity_sensor_enable_setting = info.humidity_sensor_enable_setting;
		underpressure_alarm_setting = info.underpressure_alarm_setting;
		overpressure_alarm_setting = info.overpressure_alarm_setting;
		inside_draftfan_feedback_pulse = info.inside_draftfan_feedback_pulse;
		outside_draftfan_feedback_pulse = info.outside_draftfan_feedback_pulse;
		mute_mode_setting = info.mute_mode_setting;
		system_onoff = info.system_onoff;
		buzzer_mode = info.buzzer_mode;
		lcd_contrast_setting = info.lcd_contrast_setting;
		crc2 = info.crc2;
	}

}
